import React, { useState, useRef, useEffect } from 'react';
import { FileText } from 'lucide-react';
import { useReceipt } from '../context/ReceiptContext';
import ReceiptPDF from './ReceiptPDF';
import { pdf } from '@react-pdf/renderer';
import BuyMeACoffeeModal from './BuyMeACoffeeModal';
import Swal from 'sweetalert2';

// Import new components
import ReceiptActions from './receiptDisplay/ReceiptActions';
import PDFPreviewModal from './receiptDisplay/PDFPreviewModal';
import MobileNotice from './receiptDisplay/MobileNotice';
import PrintableReceipt from './receiptDisplay/PrintableReceipt';
import ReceiptPreview from './receiptDisplay/ReceiptPreview';

const ReceiptDisplay = () => {
  const {
    receiptData,
    companyLogo,
    savedReceipts,
    saveCurrentReceipt,
    calculateSubtotal,
    calculateDiscount,
    calculateVAT,
    calculateTotal,
    calculateChange,
    formatNaira
  } = useReceipt();

  const [pdfUrl, setPdfUrl] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [showCoffeeModal, setShowCoffeeModal] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  const printableRef = useRef();

  /* ---------------- MOBILE DETECTION ---------------- */

  useEffect(() => {
    const checkMobile = () => {
      const ua = navigator.userAgent || navigator.vendor || window.opera;
      setIsMobile(/iPhone|iPad|iPod|Android|webOS|BlackBerry|IEMobile|Opera Mini/i.test(ua));
    };
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  /* ---------------- PDF CORE GENERATOR (DATA URI METHOD) ---------------- */

  const generatePDFData = async (saveToHistory = true) => {
    setIsGenerating(true);
    try {
      const pdfInstance = (
        <ReceiptPDF
          receiptData={receiptData}
          formatNaira={formatNaira}
          calculateSubtotal={calculateSubtotal}
          calculateDiscount={calculateDiscount}
          calculateVAT={calculateVAT}
          calculateTotal={calculateTotal}
          calculateChange={calculateChange}
          companyLogo={companyLogo}
        />
      );

      const blob = await pdf(pdfInstance).toBlob();

      if (saveToHistory) {
        saveCurrentReceipt(blob);
      }

      // Convert to Base64 Data URI for mobile stability
      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve({ blob, dataUri: reader.result });
        reader.onerror = () => reject(new Error("Failed to convert PDF to Data URI"));
        reader.readAsDataURL(blob);
      });
    } catch (error) {
      console.error("PDF Gen Error:", error);
      throw new Error(error.message || "Internal Rendering Error");
    } finally {
      setIsGenerating(false);
    }
  };

  /* ---------------- DOWNLOAD / SHARE ---------------- */

  const handleDownloadPDF = async () => {
    Swal.fire({
      title: 'Preparing Receipt',
      text: 'Finalizing PDF document...',
      allowOutsideClick: false,
      didOpen: () => Swal.showLoading()
    });

    try {
      const { blob } = await generatePDFData(true);
      const fileName = `${receiptData.receiptType}-${receiptData.receiptNumber}.pdf`;

      if (isMobile && navigator.share) {
        // Share API is the only 100% way to "Download" to Files on iOS/Android
        const file = new File([blob], fileName, { type: 'application/pdf' });
        await navigator.share({
          files: [file],
          title: 'Receipt PDF',
          text: 'Generated by Receipt App'
        });
        Swal.close();
      } else {
        // Desktop Standard Download
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = fileName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        
        Swal.fire({ title: "Success!", text: "Downloaded", icon: "success", timer: 2000 });
      }
      showCoffeeModalIfAllowed();
    } catch (error) {
      Swal.fire({ title: "Error", text: `Source: ${error.message}`, icon: "error" });
    }
  };

  /* ---------------- PREVIEW (DATA URI + IFRAME) ---------------- */

  const handlePreviewPDF = async () => {
    let remoteWindow = null;

    if (isMobile) {
      // Open window immediately to satisfy browser security
      remoteWindow = window.open('', '_blank');
      if (!remoteWindow) {
        Swal.fire({ title: "Popup Blocked", text: "Please allow popups to view receipt", icon: "warning" });
        return;
      }
      remoteWindow.document.write('<p style="font-family:sans-serif; text-align:center; margin-top:50px;">Generating Receipt Preview...</p>');
    }

    try {
      const { dataUri } = await generatePDFData(false);

      if (isMobile && remoteWindow) {
        // Inject an iframe with the Data URI
        remoteWindow.document.body.innerHTML = ''; // Clear loader
        remoteWindow.document.write(`
          <body style="margin:0; padding:0; overflow:hidden;">
            <iframe src="${dataUri}" width="100%" height="100%" style="border:none;" allowfullscreen></iframe>
          </body>
        `);
        remoteWindow.document.close();
      } else {
        setPdfUrl(dataUri);
        setShowPreview(true);
      }
      showCoffeeModalIfAllowed();
    } catch (error) {
      if (remoteWindow) remoteWindow.close();
      Swal.fire({ title: "Preview Error", text: `Source: ${error.message}`, icon: "error" });
    }
  };

  /* ---------------- PRINT, COPY, SHARE ---------------- */

  const handlePrint = async () => {
    try {
      const printWindow = window.open('', '_blank');
      if (!printWindow) throw new Error("Popup blocked!");
      
      printWindow.document.write(`
        <html>
          <head><title>Print Receipt</title></head>
          <body>
            ${printableRef.current.innerHTML}
            <script>setTimeout(() => { window.print(); window.close(); }, 500);</script>
          </body>
        </html>
      `);
      printWindow.document.close();
    } catch (error) {
      Swal.fire({ title: "Print Error", text: error.message, icon: "error" });
    }
  };

  const shareOnWhatsApp = async () => { /* Logic remains same as your original */ };
  const copyToClipboard = async () => { /* Logic remains same as your original */ };

  // ... (Your existing useEffect for coffee modal logic remains here) ...
  useEffect(() => {
    const today = new Date().toDateString();
    const lastShown = localStorage.getItem("coffeeModalLastShown");
    if (lastShown !== today) {
      localStorage.removeItem("coffeeModalShownToday");
      localStorage.setItem("coffeeModalLastShown", today);
    }
  }, []);

  const showCoffeeModalIfAllowed = () => {
    if (!localStorage.getItem("coffeeModalShownToday")) {
      setTimeout(() => setShowCoffeeModal(true), 1500);
      localStorage.setItem("coffeeModalShownToday", "true");
    }
  };

  return (
    <div className="space-y-6">
      <MobileNotice isMobile={isMobile} />
      <BuyMeACoffeeModal isOpen={showCoffeeModal} onClose={() => setShowCoffeeModal(false)} />
      
      <PDFPreviewModal
        isOpen={showPreview}
        onClose={() => setShowPreview(false)}
        pdfUrl={pdfUrl}
        isGenerating={isGenerating}
        onDownload={handleDownloadPDF}
        isMobile={isMobile}
      />

      <ReceiptActions
        onPrint={handlePrint}
        onDownload={handleDownloadPDF}
        onPreview={handlePreviewPDF}
        onShare={shareOnWhatsApp}
        onCopy={copyToClipboard}
        isGenerating={isGenerating}
        isMobile={isMobile}
        receiptData={receiptData}
        savedReceipts={savedReceipts}
        formatNaira={formatNaira}
        calculateTotal={calculateTotal}
        setActionCount={() => {}}
      />

      <div ref={printableRef} className="hidden">
        <PrintableReceipt
          receiptData={receiptData}
          companyLogo={companyLogo}
          formatNaira={formatNaira}
          calculateSubtotal={calculateSubtotal}
          calculateDiscount={calculateDiscount}
          calculateVAT={calculateVAT}
          calculateTotal={calculateTotal}
          calculateChange={calculateChange}
          isMobile={isMobile}
        />
      </div>

      <ReceiptPreview
        receiptData={receiptData}
        companyLogo={companyLogo}
        formatNaira={formatNaira}
        calculateSubtotal={calculateSubtotal}
        calculateVAT={calculateVAT}
        calculateTotal={calculateTotal}
      />
    </div>
  );
};

export default ReceiptDisplay;