import React, { useState, useRef, useEffect } from 'react';
import { FileText } from 'lucide-react';
import { useReceipt } from '../context/ReceiptContext';
import BuyMeACoffeeModal from './BuyMeACoffeeModal';
import Swal from 'sweetalert2';
import TemplateSelector from './receiptTemplates/TemplateSelector';
import TemplateRenderer from './receiptTemplates/TemplateRenderer';
import ReceiptActions from './receiptDisplay/ReceiptActions';
import { generatePrintHTML } from './receiptTemplates/printTemplates';
import { getPrintStyles } from '../utils/printUtils';

const ReceiptDisplay = () => {
  const {
    receiptData,
    companyLogo,
    savedReceipts,
    saveCurrentReceipt,
    calculateSubtotal,
    calculateDiscount,
    calculateVAT,
    calculateTotal,
    calculateChange,
    formatNaira,
    selectedTemplate // Get selected template from context
  } = useReceipt();

  const [isGenerating, setIsGenerating] = useState(false);
  const [showCoffeeModal, setShowCoffeeModal] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  const printableRef = useRef();

  /* ---------------- CHECK ENVIRONMENT ---------------- */
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    
    const checkMobile = () => {
      const ua = navigator.userAgent || navigator.vendor || window.opera;
      const isMobileDevice = /iPhone|iPad|iPod|Android|webOS|BlackBerry|IEMobile|Opera Mini/i.test(ua);
      setIsMobile(isMobileDevice);
    };
    
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  /* ---------------- COFFEE MODAL RESET ---------------- */
  useEffect(() => {
    if (!isClient) return;
    
    const today = new Date().toDateString();
    const lastShown = localStorage.getItem("coffeeModalLastShown");

    if (lastShown !== today) {
      localStorage.removeItem("coffeeModalShownToday");
      localStorage.setItem("coffeeModalLastShown", today);
    }
  }, [isClient]);

  const showCoffeeModalIfAllowed = () => {
    if (!isClient) return;
    
    if (!localStorage.getItem("coffeeModalShownToday")) {
      setTimeout(() => setShowCoffeeModal(true), 1500);
      localStorage.setItem("coffeeModalShownToday", "true");
    }
  };

  /* ---------------- FIXED PRINT FUNCTION ---------------- */
  const handlePrint = async () => {
    if (!isClient) {
      Swal.fire({
        title: "Error",
        text: "Please refresh the page and try again.",
        icon: "error",
        confirmButtonText: "OK"
      });
      return;
    }

    try {
      const printWindow = window.open('', '_blank');
      
      if (!printWindow) {
        Swal.fire({
          title: "Pop-up Blocked",
          text: "Please allow pop-ups for this site to print.",
          icon: "warning",
          confirmButtonText: "OK"
        });
        return;
      }
      
      // Calculate all values
      const calculations = {
        subtotal: calculateSubtotal(),
        discount: calculateDiscount(),
        vat: calculateVAT(),
        total: calculateTotal(),
        change: calculateChange(),
        deliveryFee: receiptData.deliveryFee || 0
      };
      
      // Generate the selected template HTML
      const templateHtml = generatePrintHTML(
        selectedTemplate,
        receiptData,
        companyLogo,
        formatNaira,
        calculations
      );
      
      // Get print styles
      const printStyles = getPrintStyles();
      
      // Create the complete print document
      const printDocument = `
        <!DOCTYPE html>
        <html>
          <head>
            <title>${receiptData.receiptType.toUpperCase()} ${receiptData.receiptNumber}</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="description" content="Receipt generated by ReceiptIt">
            ${printStyles}
          </head>
          <body>
            <div style="max-width: 210mm; margin: 0 auto; padding: ${isMobile ? '10mm' : '20mm'};">
              ${templateHtml}
            </div>
            
            <!-- Print Controls (Screen Only) -->
            <div class="no-print" style="
              position: fixed;
              bottom: 30px;
              right: 30px;
              display: flex;
              gap: 12px;
              z-index: 1000;
            ">
              <button onclick="window.print()" style="
                padding: 14px 28px;
                background: linear-gradient(135deg, #059669 0%, #047857 100%);
                color: white;
                border: none;
                border-radius: 8px;
                font-size: 14px;
                font-weight: 600;
                cursor: pointer;
                transition: all 0.2s;
                box-shadow: 0 4px 6px rgba(0,0,0,0.1);
              ">
                🖨️ Print / Save as PDF
              </button>
              <button onclick="window.close()" style="
                padding: 14px 28px;
                background: white;
                color: #475569;
                border: 2px solid #e2e8f0;
                border-radius: 8px;
                font-size: 14px;
                font-weight: 600;
                cursor: pointer;
              ">
                ✕ Close
              </button>
            </div>
            
            <script>
              // Auto-print for desktop (not mobile)
              setTimeout(() => {
                const isMobileDevice = ${isMobile} || window.innerWidth <= 768;
                if (!isMobileDevice) {
                  window.print();
                }
              }, 800);
              
              // Close after print
              window.addEventListener('afterprint', () => {
                setTimeout(() => window.close(), 500);
              });
            </script>
          </body>
        </html>
      `;
      
      printWindow.document.write(printDocument);
      printWindow.document.close();
      
      // Show coffee modal on main page
      showCoffeeModalIfAllowed();
      
    } catch (error) {
      console.error("Print error:", error);
      Swal.fire({
        title: "Error",
        text: "Failed to open print view. Please try again.",
        icon: "error",
        confirmButtonText: "OK"
      });
    }
  };

  /* ---------------- DOWNLOAD PDF ---------------- */
  const handleDownloadPDF = async () => {
    if (!isClient) {
      Swal.fire({
        title: "Error",
        text: "Please refresh the page and try again.",
        icon: "error",
        confirmButtonText: "OK"
      });
      return;
    }

    try {
      setIsGenerating(true);
      
      await Swal.fire({
        title: "📄 Save as PDF",
        html: `
          <div style="text-align: left; font-size: 15px;">
            <p style="margin-bottom: 15px; color: #4a5568;">Opening print view to save your receipt as PDF...</p>
            <div style="background: #f7fafc; padding: 15px; border-radius: 10px; border-left: 4px solid #4299e1;">
              <p style="font-weight: 600; color: #2d3748; margin-bottom: 10px;">📋 Instructions:</p>
              <ol style="margin-left: 20px; color: #4a5568;">
                <li style="margin-bottom: 8px;">Click <strong style="color: #2b6cb0;">"Print / Save as PDF"</strong> button</li>
                <li style="margin-bottom: 8px;">Select <strong style="color: #2b6cb0;">"Save as PDF"</strong> as printer</li>
                <li style="margin-bottom: 8px;">Choose location and save</li>
                <li>For mobile: Use browser's share menu</li>
              </ol>
            </div>
          </div>
        `,
        icon: "info",
        showCancelButton: true,
        confirmButtonText: "Open Print View",
        cancelButtonText: "Cancel",
        confirmButtonColor: "#4299e1",
        cancelButtonColor: "#a0aec0",
        timer: 8000
      }).then(async (result) => {
        if (result.isConfirmed) {
          await handlePrint();
        }
      });
      
    } catch (error) {
      console.error("Download error:", error);
      Swal.fire({
        title: "Error",
        text: "Failed to prepare download. Please try again.",
        icon: "error",
        confirmButtonText: "OK"
      });
    } finally {
      setIsGenerating(false);
    }
  };

  /* ---------------- PREVIEW PDF ---------------- */
  const handlePreviewPDF = async () => {
    if (!isClient) {
      Swal.fire({
        title: "Error",
        text: "Please refresh the page and try again.",
        icon: "error",
        confirmButtonText: "OK"
      });
      return;
    }

    try {
      // Show loading
      await Swal.fire({
        title: "Opening Preview...",
        text: "Preparing receipt for viewing",
        icon: "info",
        timer: 1500,
        showConfirmButton: false
      });
      
      await handlePrint();
      
    } catch (error) {
      console.error("Preview error:", error);
      Swal.fire({
        title: "Error",
        text: "Failed to open preview. Please try again.",
        icon: "error",
        confirmButtonText: "OK"
      });
    }
  };

  /* ---------------- COPY TO CLIPBOARD ---------------- */
  const copyToClipboard = async () => {
    if (!isClient) {
      Swal.fire({
        title: "Error",
        text: "Please refresh the page and try again.",
        icon: "error",
        confirmButtonText: "OK"
      });
      return;
    }

    try {
      const text = `
${receiptData.storeName}
${receiptData.receiptType.toUpperCase()}: ${receiptData.receiptNumber}
Date: ${receiptData.date} | Time: ${receiptData.time}
Cashier: ${receiptData.cashierName}
Template: ${selectedTemplate.toUpperCase()}

ITEMS:
${receiptData.items.map(item => 
  `${item.quantity}x ${item.name} @ ${formatNaira(item.price)} = ${formatNaira(item.price * item.quantity)}`
).join('\n')}

Subtotal: ${formatNaira(calculateSubtotal())}
${receiptData.includeDiscount ? `Discount: -${formatNaira(calculateDiscount())}\n` : ''}
${receiptData.includeVAT ? `VAT: ${formatNaira(calculateVAT())}\n` : ''}
Total: ${formatNaira(calculateTotal())}

Payment: ${receiptData.paymentMethod}
${receiptData.paymentMethod === 'Cash' && receiptData.amountPaid > 0 ? 
  `Amount Paid: ${formatNaira(receiptData.amountPaid)}\nChange: ${formatNaira(calculateChange())}\n` : ''}

${receiptData.customerNotes}

${receiptData.includeSignature ? 'Signed: _________________' : ''}

Thank you for your business!
      `.trim();

      await navigator.clipboard.writeText(text);
      
      await Swal.fire({
        title: "✅ Copied!",
        text: "Receipt text copied to clipboard",
        icon: "success",
        confirmButtonText: "OK",
        timer: 2000
      });
      
      showCoffeeModalIfAllowed();
      
    } catch (error) {
      console.error("Copy error:", error);
      Swal.fire({
        title: "Error",
        text: "Failed to copy. Please try again.",
        icon: "error",
        confirmButtonText: "OK"
      });
    }
  };

  /* ---------------- SHARE ON WHATSAPP ---------------- */
  const shareOnWhatsApp = async () => {
    if (!isClient) {
      Swal.fire({
        title: "Error",
        text: "Please refresh the page and try again.",
        icon: "error",
        confirmButtonText: "OK"
      });
      return;
    }

    try {
      const itemsList = receiptData.items.map(item =>
        `${item.quantity}x ${item.name} - ${formatNaira(item.price * item.quantity)}`
      ).join('\n');

      const text = encodeURIComponent(`
*${receiptData.receiptType.toUpperCase()} from ${receiptData.storeName}*
📄 Receipt: ${receiptData.receiptNumber}
🎨 Template: ${selectedTemplate.toUpperCase()}
📅 Date: ${receiptData.date}
⏰ Time: ${receiptData.time}
👤 Cashier: ${receiptData.cashierName}

🛒 Items:
${itemsList}

💰 Total: ${formatNaira(calculateTotal())}

${receiptData.customerNotes}

${receiptData.includeSignature ? '✍️ Signed' : ''}

Thank you for your business! 🎉
      `.trim());

      window.open(`https://wa.me/?text=${text}`, '_blank');
      
      await Swal.fire({
        title: "✅ Shared!",
        text: "WhatsApp share opened",
        icon: "success",
        confirmButtonText: "OK",
        timer: 2000
      });
      
      showCoffeeModalIfAllowed();
      
    } catch (error) {
      console.error("Share error:", error);
      Swal.fire({
        title: "Error",
        text: "Failed to open WhatsApp. Please try again.",
        icon: "error",
        confirmButtonText: "OK"
      });
    }
  };

  /* ---------------- DON'T RENDER UNTIL CLIENT-SIDE ---------------- */
  if (!isClient) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading receipt viewer...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Buy Me a Coffee Modal */}
      <BuyMeACoffeeModal
        isOpen={showCoffeeModal}
        onClose={() => setShowCoffeeModal(false)}
      />

    
      {/* Action Buttons Component */}
      <ReceiptActions
        onPrint={handlePrint}
        onDownload={handleDownloadPDF}
        onPreview={handlePreviewPDF}
        onShare={shareOnWhatsApp}
        onCopy={copyToClipboard}
        isGenerating={isGenerating}
        isMobile={isMobile}
        receiptData={receiptData}
        savedReceipts={savedReceipts}
        formatNaira={formatNaira}
        calculateTotal={calculateTotal}
        setActionCount={() => {}}
      />

      {/* Visible Preview */}
      <div className="bg-white rounded-2xl shadow-lg overflow-hidden border border-gray-200">
        <div className="p-4 border-b border-gray-200 bg-gradient-to-r from-gray-50 to-white">
          <h3 className="font-bold text-gray-800 flex items-center gap-2">
            <FileText size={18} className="text-blue-600" />
            Live Preview
            <span className="ml-2 px-2 py-0.5 bg-blue-100 text-blue-700 text-xs font-medium rounded-full">
              ${receiptData.receiptType.toUpperCase()}
            </span>
            <span className="ml-2 px-2 py-0.5 bg-purple-100 text-purple-700 text-xs font-medium rounded-full">
              ${selectedTemplate.toUpperCase()} TEMPLATE
            </span>
          </h3>
          <p className="text-sm text-gray-500 mt-1">
            This is how your receipt will look when printed
            {isMobile && <span className="ml-2 text-orange-500 font-medium">(Mobile View)</span>}
          </p>
        </div>
        <div className="p-4 sm:p-6">
          <TemplateRenderer
            receiptData={receiptData}
            companyLogo={companyLogo}
            formatNaira={formatNaira}
            calculateSubtotal={calculateSubtotal}
            calculateDiscount={calculateDiscount}
            calculateVAT={calculateVAT}
            calculateTotal={calculateTotal}
            calculateChange={calculateChange}
            isMobile={isMobile}
          />
          <div className="mt-6 pt-6 border-t border-gray-200 text-center text-sm text-gray-500">
            <p>🎯 Preview only • Click buttons above to print, save, or share</p>
            <p className="mt-1 text-xs">Selected template will be used for printing</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReceiptDisplay;